import AuthenticatedLayout from '@/components/AuthenticatedLayout';
import { Geist, Geist_Mono } from 'next/font/google';
import { ApolloWrapper } from './ApolloConfig'; // ✅ Apollo First
import './globals.css';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin']
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin']
});

// ✅ Metadata is handled at the Server level
export const metadata = {
	title: 'Tracking',
	description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				{/* ✅ Apollo First */}
				<ApolloWrapper>
					{/* ✅ Then AuthProvider (Client) */}
					{/* ✅ Move `useAuth()` to a separate Client Component */}
					<AuthenticatedLayout>{children}</AuthenticatedLayout>
				</ApolloWrapper>
			</body>
		</html>
	);
}
